/*
 * This source file was generated by the Gradle 'init' task
 */
/*
 * package mtd.tasker;
 * import mtd.tasker;
 * 
 * import org.junit.Test;
 * import static org.junit.Assert.*;
 * 
 * public class AppTest {
 * Server = new Server()
 * 
 * @Test public void appHasAGreeting() {
 * assertNotNull("app should have a greeting", classUnderTest.getGreeting());
 * }
 * 
 * @Test public void commands() {
 * assertTrue(Handler.addEvent(new Event("Max Muster", new Date(), "test")));
 * assertTrue(Handler.deleteEntry(Handler.getEvent(0).getID));
 * }
 * 
 * @Test public void run() {
 * 
 * }
 * 
 * 
 * }
 */
