@startuml

skinparam Shadowing false

participant Client as C
participant Server as S
participant Login as auth
participant Handler as H
participant GUI as G

C -> auth: Authentication Request (login())
auth -> Server: formatted Authentication Request (login())
S --> C: retrieve Latest Calendars
S --> H: format Events
C ->> S: request sync
C ->> S: request saving current Calendar to Server
S ->> C: close connection
S ->> S: kick connection
S ->> S: listen for commands
G --> G: create GUI
G --> H: send user input for formatting
H --> C: send formatted request to server 

'!include ../../plantuml-styles/ae-copyright-footer.txt
@enduml
