@startuml

skinparam Shadowing false

actor User as U
participant Client as C
participant Client as C
participant Client as C
participant Server as S
participant Login as auth
participant Handler as H
participant GUI as G
database db

U --> G: input for events
C -> : Authentication Request (login())
S -> db: authenticate user
db --> S: retrieve events
C <-- S: retrieve Latest Calendars
H <-- S: format Events
C ->> S: request sync
C <<- C: close connection
S ->> S: kick connection
S ->> S: listen for commands
G --> G: create GUI
G --> H: send user input for formatting
H --> C: send formatted request to server 

'!include ../../plantuml-styles/ae-copyright-footer.txt
@enduml
